# Generated by Django 5.2.4 on 2025-07-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_patrakaarregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrakaarMitra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('activity', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.DeleteModel(
            name='PatrakaarRegistration',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
