# Generated by Django 5.2.4 on 2025-07-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_patrakaarmitra_remove_article_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='patrakaarmitra',
            name='category',
            field=models.CharField(choices=[('journalist', 'Journalist'), ('media_partner', 'Media Partner'), ('blogger', 'Blogger')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patrakaarmitra',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
