# Generated by Django 5.2.4 on 2025-07-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_delete_category_alter_patrakaarmitra_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrakaarmitra',
            name='category',
            field=models.CharField(choices=[('journalist', 'Journalist'), ('reporter', 'Reporter'), ('editor', 'Editor'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patrakaarmitra',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
    ]
