# Generated by Django 5.2.4 on 2025-07-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_patrakaarmitra_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrakaarmitra',
            name='category',
            field=models.CharField(choices=[('Patrakaar', 'Patrakaar Mitra'), ('Reporter', 'Reporter'), ('Cameraman', 'Cameraman'), ('Member', 'Member'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patrakaarmitra',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
