# Generated by Django 5.2.4 on 2025-08-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_patrakaarmitra_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ENewsPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='enewspapers/')),
                ('published_on', models.DateField(blank=True, null=True)),
                ('uploaded_by', models.CharField(default='Administration', max_length=100)),
            ],
            options={
                'ordering': ['-published_on'],
            },
        ),
    ]
