# Generated by Django 5.2.4 on 2025-08-20 07:00

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_enewspaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enewspaper',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='enewspapers/'),
        ),
    ]
