# Generated by Django 5.2.4 on 2025-08-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_enewspaper_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enewspaper',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='enewspapers/'),
        ),
    ]
